<a href="https://colab.research.google.com/github/mohamedssafini/default_of_credit_card/blob/main/default_of_credit_card.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
example_list=list(range(1,6))

In [ ]:
example_list

[1, 2, 3, 4, 5]

In [ ]:
example_list[0]

1

In [ ]:
example_list[-1]

5

In [ ]:
example_list[-2]

4

In [ ]:
example_list[-3]

3

In [ ]:
example_list[0]='a String'

In [ ]:
example_list

['a String', 2, 3, 4, 5]

In [ ]:
example_list[:3]

['a String', 2, 3]

In [ ]:
example_list[3:]

[4, 5]

In [ ]:
for counter in range(5):
    print(counter)

0
1
2
3
4


In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('default_of_credit_card_clients__courseware_version_1_21_19.xlsx')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")


In [8]:
df.shape

(30000, 25)

In [9]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [6]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

In [7]:
df['ID'].nunique()

29687

In [10]:
id_counts = df['ID'].value_counts()
id_counts.head()

ad23fe5c-7b09    2
1fb3e3e6-a68d    2
89f8f447-fca8    2
7c9b7473-cc2f    2
90330d02-82d9    2
Name: ID, dtype: int64

In [11]:
id_counts

ad23fe5c-7b09    2
1fb3e3e6-a68d    2
89f8f447-fca8    2
7c9b7473-cc2f    2
90330d02-82d9    2
                ..
2edeb3a6-d38d    1
27e11893-92e9    1
2b1c282b-441e    1
bd737997-0eb0    1
15d69f9f-5ad3    1
Name: ID, Length: 29687, dtype: int64

In [12]:
id_counts.value_counts()

1    29374
2      313
Name: ID, dtype: int64

In [13]:
import numpy as np
from numpy.random import default_rng

In [14]:
rg = default_rng(12345)

In [15]:
random_integers = rg.integers(low=1,high=5,size=100)

In [16]:
random_integers

array([3, 1, 4, 2, 1, 4, 3, 3, 4, 2, 4, 2, 3, 3, 1, 1, 1, 3, 3, 4, 3, 1,
       4, 4, 3, 3, 1, 1, 2, 2, 1, 4, 2, 3, 1, 2, 1, 3, 4, 1, 3, 1, 2, 1,
       3, 2, 2, 2, 2, 2, 3, 4, 2, 1, 1, 1, 1, 1, 1, 3, 4, 4, 3, 3, 2, 4,
       3, 3, 3, 4, 3, 4, 3, 3, 2, 4, 3, 2, 2, 2, 3, 2, 3, 3, 4, 2, 3, 4,
       2, 2, 2, 2, 3, 2, 4, 2, 1, 1, 1, 3])

In [17]:
random_integers[:5]

array([3, 1, 4, 2, 1])

In [18]:
is_equal_to_3 = random_integers == 3

In [19]:
is_equal_to_3

array([ True, False, False, False, False, False,  True,  True, False,
       False, False, False,  True,  True, False, False, False,  True,
        True, False,  True, False, False, False,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False,  True, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False,  True,
        True, False, False,  True,  True,  True, False,  True, False,
        True,  True, False, False,  True, False, False, False,  True,
       False,  True,  True, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True])

In [20]:
sum(is_equal_to_3)

31

In [21]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3])